# SPRING
spring.application.name=ddmdemo
server.port=${API_PORT:8080}
server.address=0.0.0.0

# DATA SOURCE
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/UDDDatabase
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ana123}

# HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ELASTICSEARCH
elasticsearch.host=${ES_HOST:localhost}
elasticsearch.port=${ES_PORT:9200}
elasticsearch.username=${ES_USERNAME:elastic}
elasticsearch.password=${ES_PASSWORD:sifraElastic123}

# DOCUMENT STORAGE - MINIO
spring.minio.url=http://${MINIO_HOST:localhost}:9000
spring.minio.bucket=${MINIO_BUCKET:security-incidents}
spring.minio.access-key=${MINIO_ACCESS_KEY:admin}
spring.minio.secret-key=${MINIO_SECRET_KEY:password123}

# LOGGING
# Log file configuration
logging.file.name=logstash-ingest-data/application.log
#logging.level.com.example=DEBUG #(optional)
